name: Bug Report
description: Create a report to help us improve QuickLook
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please ensure that you have run `npm run vendor:build` if you are testing locally.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g. Windows 11, macOS Sonoma
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g. Chrome 120, Firefox 122
